# Netlify Configuration for Panda Fashion Website
# موقع مركز الباندا لأرقى الأزياء ومستلزمات التجميل

[build]
  # Build command - using npm install to include devDependencies
  command = "npm install && npm run build"
  
  # Publish directory - where the built files are located
  publish = "dist/public"
  
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Node.js version
  NODE_VERSION = "22.13.0"
  
  # NPM version
  NPM_VERSION = "10.8.3"
  
  # Force npm instead of pnpm/yarn
  NPM_FLAGS = "--legacy-peer-deps"
  
  # Environment - set to production after install
  NODE_ENV = "production"

# Function configuration
[functions]
  # Directory where functions are located
  directory = "netlify/functions"
  
  # Node bundler
  node_bundler = "esbuild"
  
  # Include files pattern
  included_files = ["dist/**", "server/**", "shared/**", "drizzle/**"]

# Redirects for API endpoints to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Redirects for client-side routing (React Router / Wouter)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

